#########注册中心配置#####################
#spring:
#  cloud:
#      nacos:
#        discovery:
#          server-addr: localhost:8848
spring:
  application:
    name: voucher
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hz_zoneservice?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

####配置打印sql
logging:
  config: classpath:logback.xml
  level:
    com.zcxd.voucher: INFO
    com.jalja.org.spring: ERROR
    org.springframework.web: ERROR
    org.apache.ibatis: INFO
    java.sql.PreparedStatement: ERROR
    java.sql.Statement: ERROR
    Java.sql.Connection: ERROR
    com.codingapi.txlcn: ERROR
    com.alibaba.nacos: error

#####redis配置
redis:
  singleServerConfig:
    address: "redis://127.0.0.1:6379"
    password: ""

mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  type-enums-package: com.zfibs.austway.enums;com.zfibs.austway.enums.*
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

services:
  filepath:
    win: D://data/
    linux: /home/finservice/hz-zone-data/
  sendpath:
    win: D://data/file/
    linux: /home/finservice/hz-zone-data/file/

#导入计划单、回款明细类型对应数据库银行id
importType:
  hzicbc: 1
  rcb: 505
  bob: 601
  jdicbc: 614

module:
  gun: true

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000 #单位毫秒,目前设置5s
        readTimeout: 5000 #单位毫秒