spring:
  profiles:
    active: local, db-dev
  application:
    name: pda
server:
  port: 8083
  max-http-header-size: 8192
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: -1